{
  "type": "file",
  "name": "layout.tsx",
  "path": "app/layout.tsx",
  "size": 1804,
  "sha": "f26537a30d67b5ba4e3f281f52107abb9c44e0ba",
  "content": "import type { Metadata } from 'next';\nimport Script from 'next/script';\nimport './globals.css';\nimport Header from '@/components/Header';\nimport Footer from '@/components/Footer';\nimport { SITE_NAME, DOMAIN, PHONE, GA4_ID } from '@/lib/data';\nimport { OG_IMAGE } from '@/lib/og';\n\nexport const metadata: Metadata = {\n  metadataBase: new URL(DOMAIN),\n  title: {\n    default: 'Middlesex County Pest Control | Licensed Exterminators NJ',\n    template: '%s',\n  },\n  description: `Expert pest control services in Middlesex County, NJ. Bed bugs, rodents, termites, mosquitoes and more. Call ${PHONE} for same-day service.`,\n  openGraph: {\n    type: 'website',\n    locale: 'en_US',\n    siteName: SITE_NAME,\n    images: [\n      {\n        url: OG_IMAGE,\n        width: 1200,\n        height: 630,\n        alt: 'Middlesex County NJ residential neighborhood',\n      },\n    ],\n  },\n  twitter: {\n    card: 'summary_large_image',\n    images: [OG_IMAGE],\n  },\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang=\"en\">\n      <head>\n        {/* Ahrefs Web Analytics */}\n        <script src=\"https://analytics.ahrefs.com/analytics.js\" data-key=\"FvYZ6FQ4LxaynlOqRZyiJw\" async />\n      </head>\n      <body>\n        {/* GA4 */}\n        <Script\n          src={`https://www.googletagmanager.com/gtag/js?id=${GA4_ID}`}\n          strategy=\"afterInteractive\"\n        />\n        <Script id=\"ga4-init\" strategy=\"afterInteractive\">\n          {`\n            window.dataLayer = window.dataLayer || [];\n            function gtag(){dataLayer.push(arguments);}\n            gtag('js', new Date());\n            gtag('config', '${GA4_ID}');\n          `}\n        </Script>\n\n        <Header />\n        <main>{children}</main>\n        <Footer />\n      </body>\n    </html>\n  );\n}\n",
  "encoding": "base64",
  "downloadUrl": "https://raw.githubusercontent.com/jeremyecker/middlesexcountypestcontrol/main/app/layout.tsx"
}
